Upgrade Scala.js version in preparation for Scala Native support
portable-scala/reflect pull request #31
Opened 2021-01-25 05:23 UTC by LeeTibbert

We align the Scala.js version patch level to that required by Scala Native.

2021-01-25 09:03 UTC, sjrd requested changes
Thank you. The first two commits LGTM. I have a few comments on the third commit, which you can `git commit --amend` to integrate the fixes into the commit rather than make a new commit.

2021-01-25 09:03 UTC, sjrd commented on .travis.yml
>      - SCALAJS_VERSION=
The empty `SCALAJS_VERSION` line should be removed. It is equivalent to `SCALAJS_VERSION=1.0.0`.

For the `SCALAJVM_VERSION` and `SCALANATIVE_VERSION`, could we set it to something non-empty, like `true` for example? That would be less awkward to read IMO.

2021-01-25 09:03 UTC, sjrd commented on build.sbt
> +                                                 NativePlatform)
I believe keeping this one line is much more readable, especially because it's chained with other method calls:
```suggestion
lazy val `portable-scala-reflect` = crossProject(JSPlatform, JVMPlatform, NativePlatform)
```

2021-01-25 09:03 UTC, sjrd commented on build.sbt
> +    mimaPreviousArtifacts := Set.empty // SN just added, no previous artifact
We use trailing commas in this build file:
```suggestion
    mimaPreviousArtifacts := Set.empty, // SN just added, no previous artifact
```

2021-01-25 09:03 UTC, sjrd commented on native/src/main/scala/org/portablescala/reflect/Reflect.scala
> +   *  In Scala.js, this method ignores the parameter `loader`. Calling this
```suggestion
   *  In Scala Native, this method ignores the parameter `loader`. Calling this
```

2021-01-25 09:03 UTC, sjrd commented on native/src/main/scala/org/portablescala/reflect/Reflect.scala
> +   *  In Scala.js, this method ignores the parameter `loader`. Calling this
```suggestion
   *  In Scala Native, this method ignores the parameter `loader`. Calling this
```

2021-01-25 18:28 UTC, sjrd approved these changes

2021-01-26 00:16 UTC, LeeTibbert commented
Sjrd: Travis CI is all green!  Thank you for all the energy you invested.

The one small change after the Approval was to change "true" to true in two places 
in `.travis.xml`.   Although I like explicit strings, I think the latter reads better in the
log file.  I have been reading a lot of those recently.  I was not quick enough 
getting that change in and only saw your Approval after it had been committed.

What is the thinking about a release? I believe that takes some
Scala Center time for tags, artifacts, etc. 

 I can study the places where the version would need to change 
 to say `1.1.0` and create an Issue listing them (as checkboxes).
 My intent is to be useful, not to push the river.

2021-01-26 00:32 UTC, LeeTibbert commented
@sideeffffect @lolgab Thank you for your contribution on bringing Scala Native support.  I think
this has been a team effort.  Of course, all remaining bugs, defects, etc. are on me.

2021-01-26 01:54 UTC, merged

2021-01-26 01:54 UTC, sjrd commented
I will take care of the release later today/tomorrow (depending on your time zone).

2021-01-26 01:56 UTC, sjrd commented
>  Of course, all remaining bugs, defects, etc. are on me.

Don't take too much credit. 😆 Remaining problems would be on me, since I approved all the code that went in.