Add documentation in the readme.
portable-scala/reflect pull request #4
Opened 2018-08-15 11:56 UTC by sjrd

2018-08-16 10:46 UTC, gzm0 requested changes

2018-08-16 10:46 UTC, gzm0 commented on README.md
> +libraryDependencies += "org.portable-scala" %%% "reflect" % "0.1.0-SNAPSHOT"
don't forget to update the artifact name

2018-08-16 10:46 UTC, gzm0 commented on README.md
> +  * `newInstance(args: Any*): Any`: invokes the constructor with the given actual arguments (which must conform to the parameter types)
I would replace all this with an example. The Scaladoc is better suited for listing existing methods (and will not get out of date).

2018-08-16 10:46 UTC, gzm0 commented on README.md
> +  * `def loadModule(): Any`: loads the singleton instance of the object
Same here. Just make an example.

2018-08-16 12:12 UTC, sjrd commented
Updated.

2018-08-17 14:35 UTC, gzm0 approved these changes

2018-08-17 14:37 UTC, merged