JVM: Don't use deprecated Class#newInstance()
portable-scala/reflect pull request #40
Opened 2021-03-31 10:31 UTC by sideeffffect

From https://github.com/portable-scala/portable-scala-reflect/pull/39#discussion_r604651184

2021-03-31 19:51 UTC, gzm0 requested changes
Only the diff issues

2021-03-31 19:51 UTC, gzm0 commented on jvm/src/main/scala/org/portablescala/reflect/InstantiatableClass.scala
> +
Spurious diff.

2021-03-31 19:51 UTC, gzm0 commented on jvm/src/main/scala/org/portablescala/reflect/InstantiatableClass.scala
> + * A wrapper for a class that can be instantiated.
Spurious diff.

2021-03-31 19:51 UTC, gzm0 commented on jvm/src/main/scala/org/portablescala/reflect/InstantiatableClass.scala
> +    runtimeClass.getConstructors.map(new InvokableConstructor(_)).toList
Spurious diff.

2021-03-31 19:51 UTC, gzm0 commented on jvm/src/main/scala/org/portablescala/reflect/InstantiatableClass.scala
> +   * Instantiates this class using its zero-argument constructor.
Spurious diff.

2021-04-01 19:07 UTC, sideeffffect commented
@gzm0 those diffs are there so that it merges well with the original PR. It seemed easier this way. Or do you think it would be better to remove them anyway?

2021-04-03 11:43 UTC, gzm0 commented
> Or do you think it would be better to remove them anyway?

Yes I think removing them would be better. We should trade the other PR if there are any conflicts.

The reason for this is that we want a single PR to change one thing only (mich easier to understand the history that way).

2021-04-03 11:51 UTC, sideeffffect commented
Sure thing! Done :heavy_check_mark:

2021-04-03 13:57 UTC, gzm0 commented
LGTM. We can merge this after you squash all the commits. (unless @sjrd has further comments).

2021-04-03 14:01 UTC, sideeffffect commented
@gzm0 I would be more than happy to do the squashing myself, but if you don't mind me asking, why don't you just do the Squash-merge of this PR yourself? GitHub makes it a trivial one-click-button operation :smile_cat:

2021-04-03 14:12 UTC, gzm0 commented
Good question :) A bunch of reasons: On one hand habit from pre-GitHub support times. However, more importantly, Scala.js (and due to its history, this repo) uses `--no-ff` merges. So every merge creates an individual merge commit, even if the branch could be fast forwarded. Or in other words: The `master` branch only contains merge commits and special (release) commits directly. GitHub does not support this flavor of squash and merge.

Why do we do this: It allows us to have PRs that have multiple meaningful commits (which we use quite extensively in Scala.js core, for example: https://github.com/scala-js/scala-js/pull/4450).

2021-04-03 15:12 UTC, sideeffffect commented
IMHO this PR is a good example where squash merge from GitHub UI would make things easier for everybody, but never mind, it's squashed now :wink:

2021-04-03 20:18 UTC, sjrd approved these changes

2021-04-03 20:22 UTC, gzm0 approved these changes

2021-04-03 20:22 UTC, merged